### ISSUE TITLE
Is pre-shared key mode supported for DTLS?

### ISSUE THREAD

**Issue by anma6543** [energomonitor/bisquitt#68]
I would like to know if pre-shared keys /PSK are supported for DTLS by the bisquitt mqtt-sn gateway ?

**Comment by mprymek** [comment]
PSK is not supported ATM unfortunately. We use https://github.com/pion/dtls library for DTLS which supports PSK so it would not be hard to add PSK support but we are not planning it for the near future. For now, our main focus is to implement the new MQTT-SN 2.x specification.
